spring.application.name=offlinepayment

server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/upimesh
spring.datasource.username=root
spring.datasource.password=chetan@7020
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

project.offlinepayment.idempotency-ttl-seconds=86400